apiVersion: v1
kind: Service
metadata:
  name: app-server-1
  namespace: default
  labels:
    app: app-server-1
    example: hpa-1
spec:
  type: ClusterIP
  selector:
    app: app-server-1
  ports:
  - port: 8000
    protocol: TCP
    targetPort: http-server

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-server-1
  labels:
    app: app-server-1
    example: hpa-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-server-1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: app-server-1
        example: hpa-1
    spec:
      containers:
        - name: server
          image: mmorejon/erase-una-vez-2:0.2.1
          imagePullPolicy: Always
          command:
            - server
          ports:
            - name: http-server
              containerPort: 8000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-client-1
  namespace: default
  labels:
    app: app-client-1
    example: hpa-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-client-1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: app-client-1
        example: hpa-1
    spec:
      containers:
        - name: client
          image: mmorejon/erase-una-vez-2:0.2.1
          imagePullPolicy: Always
          command:
            - client
          env:
            - name: SERVER_URL
              value: "http://app-server-1:8000"
            - name: ENDPOINT
              value: "/echo"
            - name: SLEEP_TIME
              value: "50ms"