apiVersion: apps/v1
kind: Deployment
metadata:
  name: volume-04
  labels:
    app: volume-04
spec:
  replicas: 1
  selector:
    matchLabels:
      app: volume-04
  template:
    metadata:
      labels:
        app: volume-04
    spec:
      containers:
        - name: example-04
          image: ghcr.io/mmorejon/erase-una-vez-1:v0.3.2
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: files
              mountPath: /srv/erase-una-vez
      volumes:
        - name: files
          image:
            reference: ghcr.io/mmorejon/erase-una-vez-5:main
            pullPolicy: IfNotPresent
