apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-01
  labels:
    app: volume-04
    type: local
spec:
  capacity:
    storage: 5Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/tmp/pv-volume-01"