apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-06
  labels:
    app: volume-06
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 100Mi
