apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim-01
  namespace: default
  labels:
    app: volume-05
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Mi