apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-05
  labels:
    app: example-05
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: example-05
  labels:
    app: example-05
spec:
  containers:
  - name: example-05
    image: ghcr.io/mmorejon/erase-una-vez-3:v0.2.1
    volumeMounts:
    - mountPath: "/srv/erase-una-vez"
      name: files
  volumes:
  - name: files
    persistentVolumeClaim:
      claimName: example-05
