apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-example-2
  labels:
    name: example-2
spec:
  replicas: 3
  selector:
    matchLabels:
      name: example-2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: example-2
    spec:
      containers:
        - image: ghcr.io/mmorejon/erase-una-vez-1:v0.3.0
          name: erase-una-vez-1
          env:
            - name: CHARACTER
              value: "un elfo."
