apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-example-6
  labels:
    name: example-6
spec:
  replicas: 3
  selector:
    matchLabels:
      name: example-6
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  template:
    metadata:
      labels:
        name: example-6
    spec:
      containers:
        - image: ghcr.io/mmorejon/erase-una-vez-1:v0.3.0
          name: erase-una-vez-1
          env:
            - name: CHARACTER
              value: "un elfo."
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pdb-example-6
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      name: example-6
