apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-example-4
  labels:
    name: example-4
spec:
  replicas: 3
  selector:
    matchLabels:
      name: example-4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  template:
    metadata:
      labels:
        name: example-4
    spec:
      containers:
        - image: ghcr.io/mmorejon/erase-una-vez-1:v0.3.2
          name: erase-una-vez-1
          env:
            - name: CHARACTER
              value: "un elfo."
          readinessProbe:
            exec:
              command:
              - /bin/cat
              - /tmp/ready
            initialDelaySeconds: 5
            failureThreshold: 1
            periodSeconds: 1
