kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: book
networking:
  apiServerAddress: "127.0.0.1"
  apiServerPort: 6443
  serviceSubnet: "10.95.0.0/22"
  podSubnet: "10.245.0.0/22"
nodes:
- role: control-plane
  image: kindest/node:v1.32.1@sha256:6afef2b7f69d627ea7bf27ee6696b6868d18e03bf98167c420df486da4662db6
  extraPortMappings:
  - containerPort: 30080
    hostPort: 80
    protocol: TCP
  - containerPort: 30443
    hostPort: 443
    protocol: TCP
  - containerPort: 30000
    hostPort: 30000
    protocol: TCP
- role: worker
  image: kindest/node:v1.32.1@sha256:6afef2b7f69d627ea7bf27ee6696b6868d18e03bf98167c420df486da4662db6
  labels:
    region: east
  extraPortMappings:
  - containerPort: 30000
    hostPort: 30001
    protocol: TCP
- role: worker
  image: kindest/node:v1.32.1@sha256:6afef2b7f69d627ea7bf27ee6696b6868d18e03bf98167c420df486da4662db6
  labels:
    region: east
  extraPortMappings:
  - containerPort: 30000
    hostPort: 30002
    protocol: TCP
- role: worker
  image: kindest/node:v1.32.1@sha256:6afef2b7f69d627ea7bf27ee6696b6868d18e03bf98167c420df486da4662db6
  labels:
    region: west
  extraPortMappings:
  - containerPort: 30000
    hostPort: 30003
    protocol: TCP
