apiVersion: v1
kind: Service
metadata:
  name: server-01
  labels:
    app: server-01
spec:
  type: ClusterIP
  selector:
    app: server-01
  ports:
    - port: 8000
      protocol: TCP
      targetPort: http-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-01
  labels:
    app: server-01
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server-01
  template:
    metadata:
      labels:
        app: server-01
    spec:
      containers:
        - name: server
          image: ghcr.io/mmorejon/erase-una-vez-2:v0.4.0
          command:
            - server
          ports:
            - name: http-server
              containerPort: 8000
