apiVersion: v1
kind: Service
metadata:
  name: server-03
  labels:
    app: server-03
    example: third
spec:
  type: NodePort
  selector:
    app: server-03
  ports:
    - port: 8000
      protocol: TCP
      targetPort: http-server
      nodePort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-03
  labels:
    app: server-03
    example: third
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server-03
  template:
    metadata:
      labels:
        app: server-03
        example: third
    spec:
      containers:
        - name: server
          image: ghcr.io/mmorejon/erase-una-vez-2:v0.4.0
          command:
            - server
          ports:
            - name: http-server
              containerPort: 8000
